import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Beauty Salon',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <Head>
      {/* <link rel="icon" href="/favicon.ico" /> */}
      <link rel="icon" sizes="16x16" href="/images/logo.webp"/>
      </Head>
      <body className={inter.className}>
      <Header></Header>
        {children}
      <Footer></Footer>
        </body>
    </html>
  )
}
